apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: cloudnative-pg-blueprint
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/edmonddantes21/cloudnative-pg-cd/cloudnative-pg-blueprint
    version: "0.1.0"